-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  table_name text NOT NULL,
  row_id uuid NOT NULL,
  operation text NOT NULL,
  old_values jsonb,
  new_values jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.authors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text UNIQUE,
  bio_en text,
  bio_am text,
  avatar_url text,
  social_links jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT authors_pkey PRIMARY KEY (id),
  CONSTRAINT authors_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  news_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_id uuid,
  content_en text NOT NULL,
  content_am text,
  is_approved boolean DEFAULT false,
  likes integer DEFAULT 0,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id)
);
CREATE TABLE public.editor_locks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  row_id uuid NOT NULL,
  admin_id uuid NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  meta jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT editor_locks_pkey PRIMARY KEY (id),
  CONSTRAINT editor_locks_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id)
);
CREATE TABLE public.knockout_matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  knockout_round_id uuid NOT NULL,
  match_id uuid,
  position integer NOT NULL,
  home_placeholder text,
  away_placeholder text,
  aggregate_home integer DEFAULT 0,
  aggregate_away integer DEFAULT 0,
  is_two_legged boolean DEFAULT false,
  first_leg_match_id uuid,
  second_leg_match_id uuid,
  winner_team_id uuid,
  next_knockout_match_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT knockout_matches_pkey PRIMARY KEY (id),
  CONSTRAINT knockout_matches_knockout_round_id_fkey FOREIGN KEY (knockout_round_id) REFERENCES public.knockout_rounds(id),
  CONSTRAINT knockout_matches_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT knockout_matches_first_leg_match_id_fkey FOREIGN KEY (first_leg_match_id) REFERENCES public.matches(id),
  CONSTRAINT knockout_matches_second_leg_match_id_fkey FOREIGN KEY (second_leg_match_id) REFERENCES public.matches(id),
  CONSTRAINT knockout_matches_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id),
  CONSTRAINT knockout_matches_next_knockout_match_id_fkey FOREIGN KEY (next_knockout_match_id) REFERENCES public.knockout_matches(id),
  CONSTRAINT knockout_matches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.knockout_rounds (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  season text NOT NULL,
  round_name text NOT NULL,
  round_order integer NOT NULL,
  total_matches integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT knockout_rounds_pkey PRIMARY KEY (id),
  CONSTRAINT knockout_rounds_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT knockout_rounds_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.leagues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug text NOT NULL UNIQUE,
  name_en text NOT NULL,
  name_am text NOT NULL,
  category text NOT NULL,
  logo_url text,
  description_en text,
  description_am text,
  founded_year integer,
  country text DEFAULT 'Ethiopia'::text,
  website_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT leagues_pkey PRIMARY KEY (id),
  CONSTRAINT leagues_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.match_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  player_id uuid,
  team_id uuid,
  minute integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['goal'::text, 'yellow'::text, 'red'::text, 'sub'::text, 'assist'::text, 'own_goal'::text, 'penalty'::text, 'match_start'::text, 'match_end'::text, 'half_time'::text, 'second_half'::text, 'injury_time'::text, 'var_check'::text, 'var_goal'::text, 'var_no_goal'::text, 'corner'::text, 'free_kick'::text, 'offside'::text, 'penalty_goal'::text, 'penalty_miss'::text, 'second_yellow'::text, 'match_pause'::text, 'match_resume'::text, 'extra_time_start'::text, 'extra_time_end'::text, 'penalty_shootout_start'::text, 'penalty_shootout_end'::text, 'penalty_shootout_scored'::text, 'penalty_shootout_missed'::text])),
  description_en text,
  description_am text,
  created_at timestamp with time zone DEFAULT now(),
  additional_data jsonb DEFAULT '{}'::jsonb,
  is_assist boolean DEFAULT false,
  subbed_in_player_id uuid,
  subbed_out_player_id uuid,
  confirmed boolean DEFAULT false,
  confirmed_by uuid,
  confirmed_at timestamp with time zone,
  CONSTRAINT match_events_pkey PRIMARY KEY (id),
  CONSTRAINT match_events_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_events_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT match_events_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT match_events_subbed_in_player_id_fkey FOREIGN KEY (subbed_in_player_id) REFERENCES public.players(id),
  CONSTRAINT match_events_subbed_out_player_id_fkey FOREIGN KEY (subbed_out_player_id) REFERENCES public.players(id),
  CONSTRAINT match_events_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.match_lineups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  team_id uuid NOT NULL,
  player_id uuid NOT NULL,
  is_starting boolean DEFAULT true,
  position text,
  jersey_number integer,
  created_at timestamp with time zone DEFAULT now(),
  captain boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  is_injured boolean DEFAULT false,
  injury_type text,
  injury_return_date date,
  injury_status text,
  position_x numeric,
  position_y numeric,
  CONSTRAINT match_lineups_pkey PRIMARY KEY (id),
  CONSTRAINT match_lineups_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_lineups_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT match_lineups_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.match_stats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  team_id uuid NOT NULL,
  possession integer DEFAULT 0,
  total_passes integer DEFAULT 0,
  pass_accuracy integer DEFAULT 0,
  total_shots integer DEFAULT 0,
  shots_on_target integer DEFAULT 0,
  shots_off_target integer DEFAULT 0,
  blocked_shots integer DEFAULT 0,
  corners integer DEFAULT 0,
  free_kicks integer DEFAULT 0,
  penalties_awarded integer DEFAULT 0,
  fouls_committed integer DEFAULT 0,
  offsides integer DEFAULT 0,
  tackles integer DEFAULT 0,
  interceptions integer DEFAULT 0,
  clearances integer DEFAULT 0,
  saves integer DEFAULT 0,
  yellow_cards integer DEFAULT 0,
  red_cards integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_stats_pkey PRIMARY KEY (id),
  CONSTRAINT match_stats_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  home_team_id uuid NOT NULL,
  away_team_id uuid NOT NULL,
  date timestamp with time zone NOT NULL,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'live'::text, 'completed'::text, 'postponed'::text, 'cancelled'::text, 'half_time'::text, 'extra_time'::text, 'penalties'::text])),
  score_home integer DEFAULT 0,
  score_away integer DEFAULT 0,
  score_detail jsonb DEFAULT '{}'::jsonb,
  minute integer DEFAULT 0,
  venue_id uuid,
  attendance integer,
  referee text,
  match_day integer,
  season text,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  round text,
  home_formation text DEFAULT '4-4-2'::text,
  away_formation text DEFAULT '4-4-2'::text,
  coach_home text,
  coach_away text,
  assistant_referee_1 text,
  assistant_referee_2 text,
  assistant_referee_3 text,
  fourth_official text,
  match_commissioner text,
  weather text,
  temperature text,
  humidity text,
  wind text,
  surface text DEFAULT 'grass'::text,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT matches_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.news (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title_en text NOT NULL,
  title_am text NOT NULL,
  slug text UNIQUE,
  content_en text,
  content_am text,
  excerpt_en text,
  excerpt_am text,
  thumbnail_url text,
  category_id uuid,
  author_id uuid,
  league_id uuid,
  match_id uuid,
  tags jsonb DEFAULT '[]'::jsonb,
  views integer DEFAULT 0,
  likes integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  is_published boolean DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT news_pkey PRIMARY KEY (id),
  CONSTRAINT news_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.news_categories(id),
  CONSTRAINT news_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(id),
  CONSTRAINT news_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT news_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT news_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.news_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  name_en text,
  name_am text,
  slug text NOT NULL UNIQUE,
  description text,
  color text,
  icon text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT news_categories_pkey PRIMARY KEY (id),
  CONSTRAINT news_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.player_injuries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  player_id uuid NOT NULL,
  team_id uuid NOT NULL,
  injury_type text NOT NULL,
  injury_date date,
  expected_return_date date,
  status text DEFAULT 'injured'::text,
  notes_en text,
  notes_am text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT player_injuries_pkey PRIMARY KEY (id),
  CONSTRAINT player_injuries_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_injuries_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT player_injuries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.players (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug text NOT NULL UNIQUE,
  team_id uuid NOT NULL,
  name_en text NOT NULL,
  name_am text NOT NULL,
  position_en text,
  position_am text,
  jersey_number integer,
  dob date,
  nationality text,
  height_cm integer,
  weight_kg integer,
  bio_en text,
  bio_am text,
  photo_url text,
  contract_until date,
  market_value text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT players_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.standings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  team_id uuid NOT NULL,
  season text NOT NULL,
  played integer DEFAULT 0,
  won integer DEFAULT 0,
  draw integer DEFAULT 0,
  lost integer DEFAULT 0,
  goals_for integer DEFAULT 0,
  goals_against integer DEFAULT 0,
  gd integer DEFAULT 0,
  points integer DEFAULT 0,
  rank integer DEFAULT 0,
  home_played integer DEFAULT 0,
  home_won integer DEFAULT 0,
  home_draw integer DEFAULT 0,
  home_lost integer DEFAULT 0,
  home_goals_for integer DEFAULT 0,
  home_goals_against integer DEFAULT 0,
  away_played integer DEFAULT 0,
  away_won integer DEFAULT 0,
  away_draw integer DEFAULT 0,
  away_lost integer DEFAULT 0,
  away_goals_for integer DEFAULT 0,
  away_goals_against integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  home_gd integer DEFAULT 0,
  away_gd integer DEFAULT 0,
  CONSTRAINT standings_pkey PRIMARY KEY (id),
  CONSTRAINT standings_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT standings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug text NOT NULL UNIQUE,
  league_id uuid NOT NULL,
  name_en text NOT NULL,
  name_am text NOT NULL,
  short_name_en text,
  short_name_am text,
  logo_url text,
  description_en text,
  description_am text,
  stadium_en text,
  stadium_am text,
  founded integer,
  website_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  league_slug text NOT NULL DEFAULT ''::text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.top_scorers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  league_id uuid NOT NULL,
  player_id uuid NOT NULL,
  team_id uuid NOT NULL,
  season text NOT NULL,
  goals integer DEFAULT 0,
  assists integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT top_scorers_pkey PRIMARY KEY (id),
  CONSTRAINT top_scorers_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id),
  CONSTRAINT top_scorers_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT top_scorers_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT top_scorers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.transfers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  player_id uuid NOT NULL,
  from_team_id uuid,
  to_team_id uuid NOT NULL,
  transfer_date date NOT NULL,
  transfer_type text NOT NULL,
  fee text,
  contract_length text,
  notes_en text,
  notes_am text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT transfers_pkey PRIMARY KEY (id),
  CONSTRAINT transfers_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT transfers_from_team_id_fkey FOREIGN KEY (from_team_id) REFERENCES public.teams(id),
  CONSTRAINT transfers_to_team_id_fkey FOREIGN KEY (to_team_id) REFERENCES public.teams(id),
  CONSTRAINT transfers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.venues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name_en text NOT NULL,
  name_am text NOT NULL,
  city text,
  capacity integer,
  address text,
  photo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  latitude numeric,
  longitude numeric,
  google_place_id text,
  surface text DEFAULT 'grass'::text,
  CONSTRAINT venues_pkey PRIMARY KEY (id),
  CONSTRAINT venues_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.views_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  news_id uuid NOT NULL,
  user_id uuid,
  ip_hash text NOT NULL,
  user_agent text,
  referrer text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT views_log_pkey PRIMARY KEY (id),
  CONSTRAINT views_log_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id),
  CONSTRAINT views_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);